# Copyright 2014 Gedare Bloom (gedare@rtems.org)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)


    bld.includes = ['.', '../shared']
    bld.shared_sources = ['../shared/init.c','../shared/workload.c'],

    bld(features = 'cxx cxxprogram',
        target = 'mstlheap.exe',
        includes = bld.includes,
        source = bld.shared_sources.extend(['pqbench.cc', 'mstlheap.cc']))


