# Copyright 2014 Gedare Bloom (gedare@rtems.org)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)


    bld.includes = ['.', '../shared']

    bld(features = 'cxx cxxprogram',
        target = 'mstlheap.exe',
        includes = bld.includes,
        source = '../shared/init.c ../shared/workload.c pqbench.cc mstlheap.cc')


